#Sat Mar 30 19:16:29 UTC 2024
micronaut:
  application:
    name: api-gateway
  server:
    port: 8083
  config-client:
    enabled: true

gateway:
  services:
    - veiculo-service
    - loja-service
    - relatorio-service

consul:
  client:
    registration:
      enabled: false
    defaultZone: "localhost:8761"