jpa:
  default:
    packagesToScan:
      'br.com.curso'
    properties:
      hibernate:
        hbm2ddl:
          auto: update

micronaut:
  application:
    name: veiculoService

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/dbveiculo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

consul:
  client:
    registration:
      enabled: false
    defaultZone: "localhost:8761"